server:
  port: 80

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.102.62.92:3306/emp?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: localhost
    port: 6379
    database: 0


mybatis:
  type-aliases-package: com.zhaimy.entity
  mapper-locations: classpath:com/zhaimy/mapper/*.xml

